# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import CummareApi.Clients.Publish_pb2 as Publish__pb2


class PublishTopicStub(object):
    """*
    Publish topic proto.

    In the PUB-SUB part, it is the PUB
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.publishMessage = channel.unary_unary(
                '/publish.PublishTopic/publishMessage',
                request_serializer=Publish__pb2.PublishRequest.SerializeToString,
                response_deserializer=Publish__pb2.PublishResponse.FromString,
                )


class PublishTopicServicer(object):
    """*
    Publish topic proto.

    In the PUB-SUB part, it is the PUB
    """

    def publishMessage(self, request, context):
        """*
        Publish a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublishTopicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'publishMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.publishMessage,
                    request_deserializer=Publish__pb2.PublishRequest.FromString,
                    response_serializer=Publish__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'publish.PublishTopic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublishTopic(object):
    """*
    Publish topic proto.

    In the PUB-SUB part, it is the PUB
    """

    @staticmethod
    def publishMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/publish.PublishTopic/publishMessage',
            Publish__pb2.PublishRequest.SerializeToString,
            Publish__pb2.PublishResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
